"""add activity to workout_sessions

Revision ID: f687f83cabe0
Revises: 7442056b9f37
Create Date: 2025-08-27 01:49:57.758316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f687f83cabe0'
down_revision: Union[str, None] = '7442056b9f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_session_exercises', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('workout_session_exercises', sa.Column('reps', sa.Integer(), nullable=True))
    op.add_column('workout_session_exercises', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('workout_sessions', sa.Column('activity', sa.String(), nullable=True))
    op.add_column('workout_sessions', sa.Column('calories', sa.Integer(), nullable=True))
    op.alter_column('workout_sessions', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.drop_column('workout_sessions', 'calories')
    op.drop_column('workout_sessions', 'activity')
    op.drop_column('workout_session_exercises', 'weight')
    op.drop_column('workout_session_exercises', 'reps')
    op.drop_column('workout_session_exercises', 'sets')
    # ### end Alembic commands ###
